### PR TITLE
fix deserialize NaN, Infinite not work with serde_json::Value

### PR DESCRIPTION
**Pull request by up9cloud**

### CODE REVIEW

**Comment by Dushistov** [comment]
@callum-oakley , any problem with this PR?

**Comment by zonyitoo** [comment]
@callum-oakley Is this project still under maintenance?

**Comment by callum-oakley** [comment]
Sorry I haven't worked on this project for a while, but I'll make some time to look at the open PRs today.

**Comment by callum-oakley** [comment]
谢谢 @up9cloud! 不好意思，我迟到了！ 😅

**Pull request merged**
