### PR TITLE
Compatible with unicode non-BMP characters

### LINKED ISSUE #26: Support Unicode Plane >= 1 represented as UTF16BE
```json
{
    "JP_flag": "\uD83C\uDDEF\uD83C\uDDF5"
}
```

This is a valid JSON, although `\uD83C` is not in valid Unicode range. It is a Japanese Nation Flag (🇯🇵), which consists of 2 Unicode Code Point `U+1F1EF, U+1F1F5`.

Since JSON's standard can only represent Unicode Plane 0 (`\u0000` - `\uFFFF`), some libraries will output it as UTF16BE, like Python.

```python
import json
v = u'\U0001F1EF\U0001F1F5'
x = json.dumps(v)
print(x)
# "\ud83c\uddef\ud83c\uddf5"
```

I think json5's parser should be able to parse these UTF16BE strings.

serde_json also supports this kind of strings: https://github.com/serde-rs/json/blob/a5b1f59df8d0554d05e3b0b5c6d9baf3a9f0a517/src/read.rs#L846-L868

### PR DESCRIPTION
**Pull request by zonyitoo**
fix #26

### CODE REVIEW

**Comment by zonyitoo** [comment]
@callum-oakley Conflict resolved.

**Comment by callum-oakley** [comment]
I had to do some reading around utf16 surrogates to understand what was going on here, but this looks sensible to me. Thanks!

**Comment by zonyitoo** [comment]
Please make a release if it is Ok.

**Comment by callum-oakley** [comment]
Incoming :)

**Comment by callum-oakley** [comment]
published as v0.3.0

**Pull request merged**
